# Generated by Django 4.2.7 on 2024-01-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techer_name', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=30)),
                ('course_duration', models.IntegerField()),
            ],
        ),
    ]
