# Generated by Django 5.0.3 on 2024-03-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='proce',
            new_name='price',
        ),
    ]
